# https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build
runtime: custom
env: flex

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml
env_variables:
  NODE_ENV: production
