name: Build

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run lint

  test-server:
    name: Test - Server
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: npm run test

  test-web:
    name: Test - Web
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies
        working-directory: web
        run: npm ci
      - name: Run test
        working-directory: web
        run: npm run test -- --watchAll=false

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies
        run: |
          npm ci --only=production &&\
          cd web && npm ci && npm run build
      - name: Build Application
        run: npm run build
