name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    container: google/cloud-sdk:264.0.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Decrypt deploy-keys.json
        run: .github/scripts/decrypt_secret.sh tools-kanziw-dev-deploy-keys.json
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      - name: Deploy to GAE
        run: |
          gcloud auth activate-service-account \
            --key-file=$HOME/secrets/tools-kanziw-dev-deploy-keys.json && \
          gcloud app deploy --project=tools-kanziw-dev
