name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Gcloud SDK
        run: brew cask install google-cloud-sdk
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies for Server
        run: npm ci
      - name: Install Dependencies for Web
        working-directory: web
        run: npm ci && npm run build
      - name: Build Application
        run: npm run build
      - name: Deploy to GAE
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo $DEPLOY_KEY > deploy-key.json
          gcloud auth activate-service-account --key-file=deploy-key.json && \
          gcloud app deploy --project=tools-kanziw-dev
          rm deploy-key.json
