name: Deploy

#on:
#  push:
#    branches:
#      - master
on: [push, pull_request]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    container: google/cloud-sdk:264.0.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Deploy to GAE
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo $DEPLOY_KEY > deploy-key.json
          gcloud auth activate-service-account --key-file=deploy-key.json
          gcloud app deploy --project=tools-kanziw-dev
          rm deploy-key.json
